// Textos de UI en español, centralizados (CLAUDE.md · docs/06 §Voz).
export const strings = {
  common: {
    appName: "Claude Solutions",
    genericError: "Algo ha fallado. Comprueba la conexión y reintenta.",
  },
  home: {
    tagline:
      "Aprende a usar Claude, de principiante a experto. En construcción.",
    login: "Iniciar sesión",
  },
  auth: {
    loginTitle: "Iniciar sesión",
    registerTitle: "Crear cuenta",
    nameLabel: "Nombre",
    emailLabel: "Email",
    passwordLabel: "Contraseña",
    passwordHint: "Mínimo 10 caracteres",
    loginSubmit: "Entrar",
    loginPending: "Entrando…",
    registerSubmit: "Crear cuenta",
    registerPending: "Creando cuenta…",
    noAccount: "¿Aún no tienes cuenta?",
    haveAccount: "¿Ya tienes cuenta?",
    logout: "Cerrar sesión",
    disabledNotice: "Cuenta desactivada. Contacta con el administrador.",
    errors: {
      passwordTooShort: "La contraseña debe tener al menos 10 caracteres.",
      invalidCredentials: "Email o contraseña incorrectos.",
      emailTaken: "Ya existe una cuenta con ese email.",
      invalidEmail: "Ese email no parece válido. Revísalo.",
    },
  },
  shell: {
    skipLink: "Saltar al contenido",
    mainNav: "Navegación principal",
    moreMenu: "Más opciones",
    more: "Más",
    profileOf: (name: string) => `Perfil de ${name}`,
    toLight: "Cambiar a tema claro",
    toDark: "Cambiar a tema oscuro",
  },
  nav: {
    dashboard: "Dashboard",
    ruta: "Ruta",
    practica: "Práctica",
    tecnicas: "Técnicas",
    progreso: "Progreso",
    perfil: "Perfil",
  },
  pages: {
    ruta: "Ruta",
    practica: "Práctica",
    tecnicas: "Técnicas",
    progreso: "Progreso",
    perfil: "Perfil",
  },
  app: {
    greeting: (name: string) => `Hola, ${name}`,
    emptyDashboard:
      "Tu espacio está listo. Empieza por la Ruta: el Nivel 0 te espera.",
    goToRoute: "Ir a la ruta",
  },
  dashboard: {
    continueTitle: "Continuar donde lo dejaste",
    startTitle: "Empieza por aquí",
    continueCta: "Continuar",
    startCta: "Empezar por aquí",
    allDone: "Todo al día. Pasa por la ruta si quieres repasar alguna lección.",
    streakTitle: "Racha",
    streakDays: (days: number) =>
      days === 1 ? "día seguido" : "días seguidos",
    streakEmpty:
      "Hoy puede empezar tu racha: completa una lección o practica 10 minutos.",
    levelTitle: "Nivel de jugador",
    xpValue: (xp: number) => `${xp} XP`,
    levelProgress: (xp: number, next: number) => `${xp} / ${next} XP`,
    levelMax: "Nivel máximo",
    levelProgressLabel: "Progreso hacia el siguiente nivel",
    reviewsTitle: "Repasos de hoy",
    reviewsEmpty:
      "Nada que repasar hoy. El tapete descansa: sigue con tu lección.",
    overdueDays: (days: number) =>
      days === 1 ? "hace 1 día" : `hace ${days} días`,
    practiceTitle: "Práctica de la semana",
    practiceEmpty:
      "Aún no has practicado esta semana. Diez minutos hoy encienden la primera barra.",
    achievementsTitle: "Últimos logros",
    achievementsEmpty:
      "Aún sin logros. Completa tu primera lección y estrena la vitrina.",
  },
  routeMap: {
    title: "Ruta",
    intro: "Seis niveles, de principiante a experto.",
    levelLabel: (id: number, name: string) => `Nivel ${id} · ${name}`,
    inPreparation: "Contenido en preparación.",
    statusAvailable: "Disponible",
    statusInProgress: (pct: number) => `En curso · ${pct}%`,
    statusCompleted: "Completado",
    statusLocked: "Bloqueado",
    lockedNeeds: (count: number, levelName: string) =>
      count === 1
        ? `Completa 1 curso de ${levelName}`
        : `Completa ${count} cursos de ${levelName}`,
    lockedPreparing: "El nivel anterior aún está en preparación.",
    progressLabel: (title: string) => `Progreso de ${title}`,
  },
  courseDetail: {
    backToRoute: "← Ruta",
    estHours: (hours: string) => `${hours} h estimadas`,
    progressText: (done: number, total: number) =>
      `${done} de ${total} lecciones`,
    start: "Empezar",
    continue: "Continuar",
    courseCompleted: "Curso completado",
    levelLockedBanner: "Este curso pertenece a un nivel todavía bloqueado.",
    lessonLockedReason: "Completa la lección anterior para desbloquearla.",
    lessonCompleted: "Completada",
    lessonLocked: "Bloqueada",
    minutes: (min: number) => `${min} min`,
    lessonTypes: {
      article: "Artículo",
      video: "Vídeo",
      practice: "Práctica",
      quiz: "Quiz",
      milestone: "Hito",
    },
  },
  lesson: {
    playVideo: (title: string) => `Reproducir vídeo: ${title}`,
    resources: "Recursos",
    previous: "Anterior",
    next: "Siguiente",
    nextLockedReason: "Siguiente bloqueada: completa esta lección primero.",
    lockedNotice: (previousTitle: string) =>
      `Esta lección está bloqueada. Completa primero «${previousTitle}».`,
    lockedNoticeFirst: "Esta lección está bloqueada.",
    goToCourse: "Ir al curso",
    breadcrumb: "Ruta de navegación",
    markComplete: "Marcar como completada",
    unmark: "Desmarcar",
    completing: "Guardando…",
    completedToast: (xp: number) => `Lección completada · +${xp} XP`,
    completedToastNoXp: "Lección completada",
    uncompletedToast: "Lección desmarcada",
    notFound: "La lección no existe o no está publicada.",
    gatePracticeChecklist:
      "Completa toda la checklist para terminar esta lección.",
    gatePracticeSession:
      "Registra al menos una sesión de práctica para completar esta lección.",
    gateQuiz: "Aprueba el quiz para completar esta lección.",
    gateMilestone: "Envía la rúbrica del hito para completarlo.",
    checklistTitle: "Checklist de práctica",
    checklistCount: (done: number, total: number) => `${done} de ${total}`,
    checklistRequired: "Requisito para completar la lección.",
    notes: "Notas",
    notesLabel: "Notas de la lección",
    notesPlaceholder: "Tus notas privadas de esta lección…",
    notesSaving: "Guardando…",
    notesSaved: "Guardado",
    notesError: "No se pudo guardar la nota. Comprueba la conexión.",
  },
  practice: {
    title: "Práctica",
    intro: "Cronómetro en marcha o sesión a mano: todo cuenta para tu racha.",
    start: "Iniciar",
    pause: "Pausar",
    resume: "Reanudar",
    finish: "Terminar",
    timerLabel: "Tiempo de práctica",
    minDuration: "La sesión mínima es de 1 minuto. Sigue un poco más.",
    dialogTitle: "Terminar sesión",
    techniqueLabel: "Técnica",
    lessonLabel: "Lección",
    noneOption: "— Sin asignar —",
    needTarget: "Elige al menos una técnica o una lección.",
    ratingLegend: "¿Cómo ha ido? (1–5)",
    notesLabel: "Notas",
    notesPlaceholder: "Qué ha salido bien, qué se atasca…",
    save: "Guardar sesión",
    saving: "Guardando…",
    savedXp: (xp: number) => `Sesión guardada · +${xp} XP`,
    savedCapped: (xp: number) =>
      `Sesión guardada · +${xp} XP · tope diario alcanzado`,
    savedRetro: "Sesión guardada · sin XP (día pasado)",
    retroNotice: "Las sesiones de días pasados no otorgan XP.",
    futureError: "La fecha no puede estar en el futuro. Revísala.",
    manualTitle: "Registrar a mano",
    dateLabel: "Fecha y hora",
    minutesLabel: "Duración (minutos)",
    historyTitle: "Historial",
    historyToday: "Hoy",
    historyWeek: "Esta semana",
    totalToday: "Hoy",
    totalWeek: "Semana",
    minutesShort: (min: number) => `${min} min`,
    ratingOf: (rating: number) => `${rating}/5`,
    emptyHistory:
      "Aún no has registrado práctica hoy. Diez minutos de doble volteo cuentan.",
    emptyCta: "Empezar cronómetro",
    dueGroup: "Para repasar hoy",
    nextReviewToast: (relative: string) => `Próximo repaso: ${relative}`,
  },
  techniques: {
    title: "Técnicas",
    categories: {
      cards: "Cartas",
      coins: "Monedas",
      mentalism: "Mentalismo",
      classics: "Clásicos",
      stage: "Escena",
      theory: "Teoría",
    } as Record<string, string>,
    intro: "El catálogo completo. Sé honesto con tu dominio: es tu mapa real.",
    categoryLabel: "Categoría",
    masteryLabel: "Dominio",
    allOption: "Todas",
    notStartedOption: "Sin empezar",
    applyFilters: "Filtrar",
    clearFilters: "Quitar filtros",
    resultsCount: (shown: number, total: number) =>
      `${shown} de ${total} técnicas`,
    emptyFilter: "Ninguna técnica coincide con esos filtros.",
    colTechnique: "Técnica",
    colCategory: "Categoría",
    colMastery: "Dominio",
    colLastPracticed: "Última práctica",
    colNextReview: "Próximo repaso",
    never: "—",
    today: "hoy",
    masteryOf: (mastery: number) => `Dominio ${mastery} de 5`,
    curriculumLevel: (id: number, name: string) => `Nivel ${id} · ${name}`,
    nextReview: "Próximo repaso",
    lastPracticed: "Última práctica",
    noDescription: "Descripción pendiente de redactar.",
    lessonsTitle: "Lecciones que la enseñan",
    lessonsEmpty: "Ninguna lección publicada la enseña todavía.",
    historyTitle: "Historial de sesiones",
    historyEmpty:
      "Aún no has practicado esta técnica. Diez minutos hoy ya cuentan.",
    historyCta: "Empezar cronómetro",
    overdueBadge: "Repaso vencido",
    editorTitle: "Tu dominio",
    editorSave: "Guardar dominio",
    editorSaving: "Guardando…",
    updatedToast: (date: string) =>
      `Dominio actualizado · próximo repaso ${date}`,
    updatedToastNoReview: "Dominio actualizado · sin repaso programado",
    // Honestidad guiada (docs/03 §E3), en el tono directo de docs/06.
    masteryDescriptors: [
      "No la conozco aún.",
      "La estoy aprendiendo paso a paso.",
      "La ejecuto mirándome las manos.",
      "La ejecuto sin mirar, hablando a la vez.",
      "Fluida ante la cámara: aguanta repeticiones.",
      "La hago ante público, bajo presión.",
    ],
  },
  progress: {
    title: "Progreso",
    intro: "Tu actividad de los últimos seis meses, de un vistazo.",
    heatmapTitle: "Actividad · 26 semanas",
    heatmapTableCaption:
      "Resumen semanal de actividad de los últimos seis meses",
    srWeek: "Semana del",
    srActiveDays: "Días activos",
    srLessons: "Lecciones",
    srMinutes: "Minutos",
    lessonsCount: (n: number) => (n === 1 ? "1 lección" : `${n} lecciones`),
    noActivity: "sin actividad",
    futureDay: "día futuro",
    categoriesTitle: "Horas por categoría",
    categoriesNote: "El total incluye sesiones sin técnica asignada.",
    categoriesEmpty:
      "Aún no hay práctica con técnica asignada. El cronómetro te espera.",
    totalLabel: "Total",
    masteryTitle: "Técnicas por dominio",
    masteryEmpty:
      "Marca tu dominio en cada técnica para ver aquí la distribución.",
    masteryCount: (n: number) => (n === 1 ? "1 técnica" : `${n} técnicas`),
    levelsTitle: "Avance por nivel",
    viewRoute: "Ver ruta",
  },
  quiz: {
    bestAttempt: (score: number, attempts: number) =>
      `Tu mejor intento: ${score}% · ${attempts === 1 ? "1 intento" : `${attempts} intentos`}`,
    unanswered: "Sin responder",
    grade: "Corregir",
    grading: "Corrigiendo…",
    resultScore: (pct: number) => `Nota: ${pct}%`,
    passed: "¡Aprobado!",
    needPct: (pct: number) => `Necesitas un ${pct}%.`,
    correct: "Correcta",
    incorrect: "Incorrecta",
    correctAnswerWas: (text: string) => `Respuesta correcta: ${text}`,
    retry: "Intentar de nuevo",
    completeCta: "Marcar lección como completada",
    noQuestions:
      "Este quiz aún no tiene preguntas; no se puede completar todavía.",
    noQuestionsEyebrow: "Quiz en preparación",
  },
  milestone: {
    rubricTitle: "Autoevaluación",
    anchors: "1 · Necesita trabajo — 5 · Listo para público",
    reflectionLabel: "Reflexión",
    reflectionPlaceholder:
      "¿Qué salió bien? ¿Qué repetirías distinto? ¿Lo grabaste en vídeo?",
    save: "Guardar autoevaluación",
    saving: "Guardando…",
    savedToast: (average: string) => `Rúbrica guardada · media ${average}`,
    completeCta: "Marcar hito como completado",
    repeat: "Repetir autoevaluación",
    historyTitle: "Historial de autoevaluaciones",
    averageLabel: (average: string) => `media ${average}`,
    incomplete: "Puntúa todos los criterios para guardar.",
    noReflection: "Sin reflexión.",
  },
  achievements: {
    toast: (name: string) => `🏆 Logro: ${name}`,
    showcaseTitle: "Vitrina de logros",
    counter: (earned: number, total: number) => `${earned} de ${total}`,
    earnedOn: (date: string) => `Conseguido el ${date}`,
    profileEditPending: "La edición de perfil llegará más adelante.",
    seeProfile: "Ver perfil",
  },
  admin: {
    title: "Claude Solutions · Admin",
    backToApp: "← Volver a la app",
    nav: {
      resumen: "Resumen",
      cursos: "Cursos",
      lecciones: "Lecciones",
      tecnicas: "Técnicas",
      quizzes: "Quizzes",
      usuarios: "Usuarios",
    },
    summary: {
      title: "Resumen de contenidos",
      courses: "Cursos",
      lessons: "Lecciones",
      modules: "Módulos",
      techniques: "Técnicas",
      users: "Usuarios",
      manageCourses: "Gestionar cursos",
      byStatus: (draft: number, published: number, archived: number) =>
        `${published} publicados · ${draft} borradores · ${archived} archivados`,
    },
    courses: {
      title: "Cursos",
      newCourse: "Nuevo curso",
      colTitle: "Título",
      colLevel: "Nivel",
      colOrder: "Orden",
      colStatus: "Estado",
      colContent: "Módulos / Lecciones",
      colUpdated: "Actualizado",
      statusLabel: {
        draft: "Borrador",
        published: "Publicado",
        archived: "Archivado",
      } as Record<string, string>,
      filterStatus: "Estado",
      filterLevel: "Nivel",
      allOption: "Todos",
      apply: "Filtrar",
      clear: "Quitar filtros",
      empty: "Ningún curso coincide con esos filtros.",
    },
    form: {
      createTitle: "Nuevo curso",
      titleLabel: "Título",
      slugLabel: "Slug",
      slugHint: "minúsculas-y-guiones; se sugiere desde el título",
      levelLabel: "Nivel",
      orderLabel: "Orden en el nivel",
      orderAutoHint: "Vacío = siguiente libre",
      hoursLabel: "Horas estimadas",
      requiredLabel: "Obligatorio para desbloquear el nivel siguiente",
      statusLabel: "Estado",
      summaryLabel: "Resumen",
      descriptionLabel: "Descripción (markdown)",
      save: "Guardar",
      saving: "Guardando…",
      created: "Curso creado",
      saved: "Cambios guardados",
    },
    modulesSection: {
      title: "Módulos",
      colOrder: "Orden",
      colTitle: "Título",
      colLessons: "Lecciones",
      addTitlePlaceholder: "Título del módulo nuevo",
      add: "Añadir módulo",
      saveRow: "Guardar",
      deleteRow: "Borrar",
      created: "Módulo creado",
      saved: "Módulo guardado",
      deleted: "Módulo borrado",
      empty: "Este curso aún no tiene módulos.",
    },
    actions: {
      publish: "Publicar",
      archive: "Archivar",
      deleteCourse: "Borrar curso",
      statusSaved: "Estado actualizado",
      cancel: "Cancelar",
      confirmDelete: "Borrar definitivamente",
      deleteCourseTitle: "Borrar curso",
      deleteCourseBody: (title: string, modules: number, lessons: number) =>
        `Vas a borrar «${title}» con sus ${modules} módulos y ${lessons} lecciones. No hay vuelta atrás.`,
      deleteModuleTitle: "Borrar módulo",
      deleteModuleBody: (title: string, lessons: number) =>
        `Vas a borrar «${title}» y sus ${lessons} lecciones. No hay vuelta atrás.`,
      hasProgressBody:
        "Hay alumnos con progreso en este contenido: no se puede borrar. Archívalo y desaparecerá del catálogo conservando el historial.",
      archiveInstead: "Archivar en su lugar",
      courseDeleted: "Curso borrado",
      archived: "Curso archivado",
    },
    lessons: {
      title: "Lecciones",
      newLesson: "Nueva lección",
      colTitle: "Título",
      colWhere: "Curso → Módulo",
      colType: "Tipo",
      colStatus: "Estado",
      colOrder: "Orden",
      colUpdated: "Actualizada",
      filterCourse: "Curso",
      filterType: "Tipo",
      filterStatus: "Estado",
      allOption: "Todos",
      apply: "Filtrar",
      clear: "Quitar filtros",
      empty: "Ninguna lección coincide con esos filtros.",
    },
    lessonForm: {
      createTitle: "Nueva lección",
      titleLabel: "Título",
      slugLabel: "Slug",
      slugHint: "minúsculas-y-guiones; se sugiere desde el título",
      moduleLabel: "Módulo",
      typeLabel: "Tipo",
      durationLabel: "Duración (min)",
      xpLabel: "XP (vacío = por tipo)",
      statusLabel: "Estado",
      videoLabel: "URL del vídeo",
      videoDetected: (provider: string) => `${provider} detectado`,
      videoProviders: {
        youtube: "YouTube",
        vimeo: "Vimeo",
        file: "Archivo de vídeo",
      } as Record<string, string>,
      videoUnrecognized: "URL no reconocida",
      contentLabel: "Contenido (markdown)",
      editTab: "Editar",
      previewTab: "Vista previa",
      previewEmpty: "Escribe markdown para ver la vista previa.",
      uploadImage: "Subir imagen",
      uploading: "Subiendo…",
      imageAltPlaceholder: "descripción",
      save: "Guardar",
      saving: "Guardando…",
      created: "Lección creada",
      saved: "Cambios guardados",
    },
    checklistEditor: {
      title: "Checklist / rúbrica",
      addPlaceholder: "Texto del punto nuevo",
      add: "Añadir punto",
      moveUp: "Subir",
      moveDown: "Bajar",
      save: "Guardar",
      remove: "Borrar",
      created: "Punto añadido",
      saved: "Punto guardado",
      deleted: "Punto borrado",
      empty: "Esta lección no tiene puntos de checklist.",
      deleteTitle: "Borrar punto",
      deleteBody: (text: string) =>
        `Vas a borrar «${text}». No hay vuelta atrás.`,
      blockedBody:
        "Hay alumnos que ya han marcado este punto (o el hito tiene entregas): no se puede borrar.",
    },
    techniquesPicker: {
      title: "Técnicas asociadas",
      save: "Guardar técnicas",
      saved: "Técnicas guardadas",
      empty: "No hay técnicas en el catálogo.",
      count: (n: number) => (n === 1 ? "1 seleccionada" : `${n} seleccionadas`),
    },
    resourcesEditor: {
      title: "Recursos",
      kindLabel: "Tipo",
      kinds: {
        pdf: "PDF",
        image: "Imagen",
        link: "Enlace",
        file: "Archivo",
      } as Record<string, string>,
      titlePlaceholder: "Título del recurso",
      urlPlaceholder: "https://… o /uploads/…",
      add: "Añadir recurso",
      save: "Guardar",
      remove: "Borrar",
      moveUp: "Subir",
      moveDown: "Bajar",
      created: "Recurso añadido",
      saved: "Recurso guardado",
      deleted: "Recurso borrado",
      empty: "Esta lección no tiene recursos.",
      deleteTitle: "Borrar recurso",
      deleteBody: (title: string) =>
        `Vas a borrar «${title}». No hay vuelta atrás.`,
    },
    lessonActions: {
      publish: "Publicar",
      archive: "Archivar",
      deleteLesson: "Borrar lección",
      statusSaved: "Estado actualizado",
      archived: "Lección archivada",
      deleted: "Lección borrada",
      deleteTitle: "Borrar lección",
      deleteBody: (title: string, items: number, resources: number) =>
        `Vas a borrar «${title}» con sus ${items} puntos de checklist y ${resources} recursos. No hay vuelta atrás.`,
      hasProgressBody:
        "Hay alumnos con progreso en esta lección: no se puede borrar. Archívala y desaparecerá del curso conservando el historial.",
      archiveInstead: "Archivar en su lugar",
      archiveBody: (title: string) =>
        `«${title}» dejará de verse en el curso; el progreso se conserva.`,
    },
    uploads: {
      missingFile: "Falta el archivo.",
      tooBig: "La imagen supera el límite de 5 MB.",
      badType: "Formato no admitido: solo PNG, JPEG, WebP o GIF.",
      extMismatch: "La extensión del archivo no coincide con su tipo.",
      badContent: "El contenido del archivo no coincide con su tipo declarado.",
      uploaded: "Imagen insertada en el contenido",
      failed: "No se pudo subir la imagen.",
    },
    reorder: {
      moveUp: "Subir",
      moveDown: "Bajar",
      structureTitle: "Estructura del curso",
      structureLessonsEmpty: "Sin lecciones.",
    },
    techniques: {
      title: "Técnicas",
      newTechnique: "Nueva técnica",
      colName: "Nombre",
      colCategory: "Categoría",
      colLevel: "Nivel",
      colLessons: "Lecciones",
      filterCategory: "Categoría",
      filterLevel: "Nivel",
      allOption: "Todas",
      apply: "Filtrar",
      clear: "Quitar filtros",
      empty: "Ninguna técnica coincide con esos filtros.",
      form: {
        createTitle: "Nueva técnica",
        nameLabel: "Nombre",
        slugLabel: "Slug",
        slugHint: "minúsculas-y-guiones; se sugiere desde el nombre",
        categoryLabel: "Categoría",
        levelLabel: "Nivel",
        descriptionLabel: "Descripción (markdown)",
        save: "Guardar",
        saving: "Guardando…",
        created: "Técnica creada",
        saved: "Cambios guardados",
      },
      actions: {
        deleteTechnique: "Borrar técnica",
        deleteTitle: "Borrar técnica",
        deleteCleanBody: (name: string) =>
          `Vas a borrar «${name}». No hay vuelta atrás.`,
        deleteLinkedBody: (name: string, lessons: number) =>
          `«${name}» está vinculada a ${lessons === 1 ? "1 lección" : `${lessons} lecciones`}; el vínculo se borrará con ella. No hay vuelta atrás.`,
        inUseBody:
          "Hay alumnos con práctica o dominio registrados en esta técnica: no se puede borrar.",
        deleted: "Técnica borrada",
      },
    },
    quizzes: {
      title: "Quizzes",
      colLesson: "Lección",
      colWhere: "Curso → Módulo",
      colState: "Estado",
      colPassPct: "Nota mínima",
      stateNoQuiz: "Sin quiz",
      stateNoQuestions: "Sin preguntas",
      stateSummary: (questions: number, attempts: number) =>
        `${questions === 1 ? "1 pregunta" : `${questions} preguntas`} · ${attempts === 1 ? "1 intento" : `${attempts} intentos`}`,
      empty: "No hay lecciones de tipo quiz.",
      editor: {
        backToList: "Quizzes",
        createQuiz: "Crear quiz",
        created: "Quiz creado",
        passPctLabel: "Nota mínima (%)",
        savePassPct: "Guardar nota",
        passPctSaved: "Nota mínima guardada",
        attemptsWarning:
          "Este quiz ya tiene intentos: las notas pasadas no se recalculan al editar preguntas u opciones.",
        questionsTitle: "Preguntas",
        promptLabel: "Enunciado",
        kindLabel: "Tipo",
        kinds: { single: "Única correcta", truefalse: "Verdadero / Falso" },
        explanationLabel: "Explicación (opcional)",
        optionsLabel: "Opciones",
        correctLabel: "Correcta",
        optionTextLabel: "Texto de la opción",
        addOption: "Añadir opción",
        removeOption: "Quitar",
        addQuestionTitle: "Nueva pregunta",
        addQuestion: "Añadir pregunta",
        saveQuestion: "Guardar pregunta",
        questionSaved: "Pregunta guardada",
        questionCreated: "Pregunta añadida",
        deleteQuestion: "Borrar pregunta",
        deleteQuestionTitle: "Borrar pregunta",
        deleteQuestionBody: (prompt: string) =>
          `Vas a borrar «${prompt}». No hay vuelta atrás.`,
        questionDeleted: "Pregunta borrada",
        hasAttemptsBody:
          "Este quiz tiene intentos de alumnos: no se puede borrar. El histórico de notas depende de él.",
        deleteQuiz: "Borrar quiz",
        deleteQuizTitle: "Borrar quiz",
        deleteQuizBody: (questions: number) =>
          `Vas a borrar el quiz con sus ${questions} preguntas. No hay vuelta atrás.`,
        quizDeleted: "Quiz borrado",
        noQuestions: "Este quiz aún no tiene preguntas.",
        editInLesson: "Editar lección",
        editQuiz: "Editar quiz",
      },
    },
    users: {
      title: "Usuarios",
      colName: "Nombre",
      colEmail: "Email",
      colRole: "Rol",
      colXp: "XP",
      colSignup: "Registro",
      colState: "Estado",
      roleLabels: { student: "Alumno", admin: "Admin" } as Record<
        string,
        string
      >,
      stateActive: "Activa",
      stateDisabled: "Desactivada",
      youTag: "(tú)",
      makeAdmin: "Hacer admin",
      makeStudent: "Quitar admin",
      disable: "Desactivar",
      enable: "Reactivar",
      roleDialogTitle: "Cambiar rol",
      roleDialogBody: (name: string, role: string) =>
        `${name} pasará a tener rol ${role}.`,
      disableDialogTitle: "Desactivar cuenta",
      disableDialogBody: (name: string) =>
        `${name} no podrá entrar hasta que se reactive la cuenta. Su progreso se conserva.`,
      enableDialogTitle: "Reactivar cuenta",
      enableDialogBody: (name: string) => `${name} podrá volver a entrar.`,
      confirm: "Confirmar",
      roleSaved: "Rol actualizado",
      disabledSaved: "Cuenta desactivada",
      enabledSaved: "Cuenta reactivada",
      lastAdminError:
        "Es el único admin activo: el sistema no puede quedarse sin administrador.",
      empty: "No hay usuarios.",
    },
    courseOrderTaken: "Ya hay un curso con ese orden en este nivel.",
    moduleOrderTaken: "Ya hay un módulo con ese orden en este curso.",
    slugTaken: "Ya existe un curso con ese slug.",
    lessonOrderTaken: "Ya hay una lección con ese orden en este módulo.",
    lessonSlugTaken: "Ya existe una lección con ese slug.",
    lessonTypeLocked:
      "No se puede cambiar el tipo: la lección tiene un quiz con preguntas, intentos o entregas asociadas.",
    techniqueSlugTaken: "Ya existe una técnica con ese slug.",
  },
} as const;
